apiVersion: v2
name: osdfir-infrastructure
version: 0.1.0
description: A Helm chart for Open Source Digital Forensics Kubernetes deployments.
keywords:
- timesketch
- turbinia
- dfir
- analysis
- processing
- cloud
home: "https://github.com/google/osdfir-infrastructure"
dependencies:
- condition: timesketch.enabled
  name: timesketch
  repository: file://charts/timesketch
- condition: turbinia.enabled
  name: turbinia
  repository: file://charts/turbinia
maintainers:
  - name: wajihyassine
sources:
- https://github.com/google/osdfir-infrastructure
- https://github.com/google/turbinia
- https://github.com/google/timesketch
icon: https://raw.githubusercontent.com/google/timesketch/master/timesketch/frontend-ng/dist/timesketch-color.png
appVersion: "0.1.0"
annotations:
  category: Security
  licenses: Apache-2.0