## OSDFIR Infrastructure Helm Chart
## Please use this Helm chart for deploying Open Source Digital Forensics Tools
## to a Kubernetes environment. 
## The following tools are supported in this deployment:
## - Timesketch; ref https://github.com/google/timesketch
## - Turbinia; ref https://github.com/google/turbinia
##
## @section Timesketch configuration
## The following section covers configuration parameters for Timesketch
## To see a full list of available values, run helm show values charts/timesketch*
##
timesketch:
  enabled: true
  redis:
    nameOverride: timesketch-redis
## @section Turbinia configuration
## The following section covers configuration parameters for Turbinia
## To see a full list of available values, run helm show values charts/turbinia*
##
turbinia:
  enabled: true
  redis:
    nameOverride: turbinia-redis