apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "turbinia.pvc.name"  . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- include "turbinia.storage.class" . | nindent 2 }}
  accessModes:
  {{- include "turbinia.storage.accessModes" . | nindent 4 }}
  resources:
    requests:
      storage: {{ include "turbinia.storage.size"  . }}